Repository devexperts/dxcharts-lite, pull requests merged in 2023-09, with the labels that each got.

#19 fix: vertical grid alignment
  src/chart/components/grid/grid.drawer.ts
  src/chart/drawers/chart-type-drawers/candle.drawer.ts
Labels: bug

#8 feat!: y axis refactoring
  src/chart/bootstrap.ts
  src/chart/canvas/canvas-bounds-container.ts
  src/chart/canvas/y-axis-bounds.container.ts
  src/chart/chart.config.ts
  src/chart/components/chart/chart.model.ts
  src/chart/components/chart/price.formatter.ts
  src/chart/components/cross_tool/types/cross-and-labels.drawer.ts
  src/chart/components/grid/grid.component.ts
  src/chart/components/grid/grid.drawer.ts
  src/chart/components/labels_generator/numeric-axis-labels.generator.ts
  src/chart/components/pane/extent/y-extent-component.ts
  src/chart/components/pane/pane-manager.component.ts
  src/chart/components/pane/pane.component.ts
  src/chart/components/volumes/separate-volumes.component.ts
  src/chart/components/volumes/volumes.component.ts
  src/chart/components/y_axis/numeric-y-axis-labels.generator.ts
  src/chart/components/y_axis/price_labels/data-series-y-axis-labels.provider.ts
  src/chart/components/y_axis/price_labels/last-candle-labels.provider.ts
  src/chart/components/y_axis/price_labels/price-label.drawer.ts
  src/chart/components/y_axis/price_labels/y-axis-labels.model.ts
  src/chart/components/y_axis/price_labels/y-axis-price-labels.drawer.ts
  src/chart/components/y_axis/y-axis-base-labels.model.ts
  src/chart/components/y_axis/y-axis-labels.drawer.ts
  src/chart/components/y_axis/y-axis-scale.handler.ts
  src/chart/components/y_axis/y-axis.component.ts
  src/chart/components/y_axis/y-axis.drawer.ts
  src/chart/components/y_axis/y-axis.model.ts
  src/chart/drawers/drawing-manager.ts
  src/chart/drawers/ht-data-series.drawer.ts
  src/chart/inputhandlers/chart-resize.handler.ts
  src/chart/model/data-series-view.ts
  src/chart/model/data-series.model.ts
  src/chart/model/hit-test-canvas.model.ts
  src/chart/model/scale.model.ts
  src/chart/model/scaling/viewport.model.ts
  src/chart/model/time-zone.model.ts
  src/chart/utils/performance/animation-frame-cache.utils.ts
  src/chart/utils/performance/debounce.utils.ts
  src/chart/utils/performance/memoize.utils.ts
  src/chart/utils/performance/request-animation-frame-throttle.utils.ts
  src/chart/utils/performance/throttle.utils.ts
  src/chart/utils/price-increments.utils.ts
Labels: enhancement

#23 fix: y-extent idx & last candle label appearance
  src/chart/bootstrap.ts
  src/chart/components/pane/pane-hit-test.controller.ts
  src/chart/components/y_axis/price_labels/last-candle-labels.provider.ts
  src/chart/components/y_axis/y-axis.model.ts
Labels: bug

#25 feat: handle double tap for mobile version
  src/chart/inputlisteners/canvas-input-listener.component.ts
Labels: enhancement

#30 feat: add removeCandleByIdx method
  src/chart/components/chart/chart-base.model.ts
  src/chart/components/chart/chart.component.ts
  src/chart/components/chart/chart.model.ts
Labels: enhancement

#31 chore: add keywords
  package.json
Labels: documentation

#35 feat!: changed the API of dynamic objects model
  src/chart/components/chart/chart.component.ts
  src/chart/components/dynamic-objects/dynamic-objects.model.ts
  src/chart/components/volumes/volumes.component.ts
  src/chart/components/volumes/volumes.model.ts
Labels: enhancement

#39 fix: show crosstool after longtouch
  src/chart/components/cross_tool/cross-tool.model.ts
  src/chart/inputhandlers/hover-producer.component.ts
Labels: bug

#37 fix: update y axis labels when last candle value changes
  src/chart/components/chart/chart.model.ts
Labels: bug
