Repository devexperts/dxcharts-lite, pull requests merged in 2023-10, with the labels that each got.

#47 feat: added some nice dynamic objects model methods
  src/chart/components/dynamic-objects/dynamic-objects.model.ts
Labels: enhancement

#48 fix: fixed LinkedList methods errors + refactored dynamic objects mod…
  src/chart/components/dynamic-objects/dynamic-objects.model.ts
  src/chart/utils/linkedList.utils.ts
Labels: bug, enhancement

#59 fix: type and main fields added to config
  package.json
Labels: enhancement

#61 fix!: fixed click/mousedown/mouseup events to be triggerd only on lef…
  src/chart/inputlisteners/canvas-input-listener.component.ts
Labels: bug
