Repository devexperts/dxcharts-lite, pull requests merged in 2023-08, with the labels that each got.

#1 fix: fix multiple extents example
  docs/how-to/multiple-y-scales/README.md
  docs/how-to/multiple-y-scales/index.html
Labels: bug, documentation

#3 chore: add unit tests for clamp math util
  src/chart/utils/__tests__/math.utils.test.ts
Labels: tests

#15 feat!: support-reordering
  docs/how-to/add-events/index.html
  docs/how-to/custom-drawer/README.md
  docs/how-to/custom-drawer/index.html
  src/chart/bootstrap.ts
  src/chart/canvas/canvas-chart-html.ts
  src/chart/canvas/chart-elements.ts
  src/chart/chart.config.ts
  src/chart/components/chart/chart.component.ts
  src/chart/components/dynamic-objects/dynamic-objects.component.ts
  src/chart/components/dynamic-objects/dynamic-objects.drawer.ts
  src/chart/components/dynamic-objects/dynamic-objects.model.ts
  src/chart/components/pane/extent/y-extent-component.ts
  src/chart/components/pane/pane-manager.component.ts
  src/chart/components/pane/pane.component.ts
  src/chart/components/snapshot/snapshot.component.ts
  src/chart/components/volumes/separate-volumes.component.ts
  src/chart/components/volumes/volumes.component.ts
  src/chart/components/volumes/volumes.drawer.ts
  src/chart/components/watermark/water-mark.component.ts
  src/chart/drawers/data-series.drawer.ts
  src/chart/drawers/drawing-manager.ts
  src/chart/model/data-series.model.ts
  src/chart/utils/linkedList.utils.ts
Labels: enhancement, help wanted
